//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EloDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameScore
    {
        public int GameID { get; set; }
        public int PlayerID { get; set; }
        public float Score { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }
    }
}
