//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EloDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.GameScores = new HashSet<GameScore>();
        }
    
        public int GameID { get; set; }
        public int GameTypeID { get; set; }
    
        public virtual GameType GameType { get; set; }
        public virtual ICollection<GameScore> GameScores { get; set; }
    }
}
